### ISSUE TITLE
Load model

### ISSUE THREAD

**Issue by hbwu-ntu** [kkoutini/passt_hear21#4]
Can I download the model locally rather than using the _create_vision_transformer to download the model?

As I have to run the code on a server that can not access the public network, can I just use a local ".pt" file?

**Comment by kkoutini** [comment]
Hi, 
I think the simplest way to do it is to store the downloaded models locally in the torch hub cache directory. It should be by default:
```
~/.cache/torch/hub/checkpoints/
```
You can also change it : [documentation](https://pytorch.org/docs/stable/hub.html#where-are-my-downloaded-models-saved).

You can find the links to download the pre-trained models [here](https://github.com/kkoutini/passt_hear21/blob/ddce36e9d5f1d8e24829ded754e72fb06314126e/hear21passt/models/passt.py#L164). The default one is [passt-s-f128-p16-s10-ap.476-swa.pt](https://github.com/kkoutini/PaSST/releases/download/v0.0.1-audioset/passt-s-f128-p16-s10-ap.476-swa.pt) (chosen by default [here](https://github.com/kkoutini/passt_hear21/blob/ddce36e9d5f1d8e24829ded754e72fb06314126e/hear21passt/models/passt.py#L799) ).

**Comment by hbwu-ntu** [comment]
Thank you very much, and it is really helpful. By the way, can I use another way:
1. Download the model
2. Delete this line (https://github.com/kkoutini/passt_hear21/blob/main/hear21passt/models/passt.py#L165) and then load a randomly initialized model.
3. Then use the local file to load the state_dict of the model
`sd = torch.load("/path/pretrained_model/passt-s-f128-p16-s10-ap.476-swa.pt", map_location="cpu")
model.net.load_state_dict(sd, strict=False)`

I tried this way and I think this way also works.

**Comment by kkoutini** [comment]
Hi, 
I also think this should work. Although I think maybe it would be a good idea to leave `strict=True`, so that loading the model would fail if, for example, the positional encodings don't match. This can happen if, for example, `input_tdim`, `input_fdim`, `fstride` or `tstride`  are different from the pre-trained model values. If the weights don't match, the loading code will fail silently (with a warning). The inference, however, will be calculated without the trained positional encodings, resulting in bad embeddings/results.

**Comment by hbwu-ntu** [comment]
Thank you for your reply. Actually, I tried `strict=True`, and it also works.

Nice work, and many thanks for your contributions.

**Comment by kkoutini** [comment]
Thank you :) I hope it is helpfu
